_SECTOR_MAP = {
    # Technology
    "AAPL": "technology", "MSFT": "technology", "GOOGL": "technology", "GOOG": "technology",
    "AMZN": "technology", "META": "technology", "NVDA": "technology", "AMD": "technology",
    "INTC": "technology", "CRM": "technology", "ADBE": "technology", "ORCL": "technology",
    "CSCO": "technology", "QCOM": "technology", "TXN": "technology", "AVGO": "technology",
    "IBM": "technology", "NOW": "technology", "UBER": "technology", "PYPL": "technology",
    "PANW": "technology", "CRWD": "technology", "SNOW": "technology", "DDOG": "technology",
    "PLTR": "technology", "MU": "technology", "AMAT": "technology", "KLAC": "technology",
    "LRCX": "technology", "ADI": "technology", "MCHP": "technology", "SMCI": "technology",
    "ANET": "technology", "WDAY": "technology", "TEAM": "technology", "ZS": "technology",
    "NET": "technology", "MDB": "technology",

    # Healthcare
    "UNH": "healthcare", "LLY": "healthcare", "JNJ": "healthcare", "PFE": "healthcare",
    "ABBV": "healthcare", "MRK": "healthcare", "TMO": "healthcare", "ABT": "healthcare",
    "DHR": "healthcare", "BMY": "healthcare", "AMGN": "healthcare", "ISRG": "healthcare",
    "SYK": "healthcare", "VRTX": "healthcare", "REGN": "healthcare", "GILD": "healthcare",
    "BSX": "healthcare", "EW": "healthcare", "ZTS": "healthcare", "MRNA": "healthcare",
    "ILMN": "healthcare", "IDXX": "healthcare", "DXCM": "healthcare", "PODD": "healthcare",
    "ALGN": "healthcare", "INCY": "healthcare", "UTHR": "healthcare",

    # Financials
    "JPM": "financials", "BAC": "financials", "WFC": "financials", "GS": "financials",
    "MS": "financials", "C": "financials", "AXP": "financials", "V": "financials",
    "MA": "financials", "BLK": "financials", "SCHW": "financials", "USB": "financials",
    "PNC": "financials", "TFC": "financials", "COF": "financials", "FITB": "financials",
    "KEY": "financials", "MTB": "financials", "CFG": "financials", "HBAN": "financials",
    "RF": "financials", "CMA": "financials", "ZION": "financials",

    # Consumer Cyclical
    "TSLA": "consumer_cyclical", "F": "consumer_cyclical", "GM": "consumer_cyclical",
    "NKE": "consumer_cyclical", "HD": "consumer_cyclical", "LOW": "consumer_cyclical",
    "SBUX": "consumer_cyclical", "MCD": "consumer_cyclical", "CMG": "consumer_cyclical",
    "DRI": "consumer_cyclical", "YUM": "consumer_cyclical", "RCL": "consumer_cyclical",
    "CCL": "consumer_cyclical", "NCLH": "consumer_cyclical", "MAR": "consumer_cyclical",
    "HLT": "consumer_cyclical", "BKNG": "consumer_cyclical", "ABNB": "consumer_cyclical",
    # AMZN is in both tech and consumer,
    "TGT": "consumer_cyclical", "WMT": "consumer_staples", # WMT is staples,
    "COST": "consumer_cyclical", "LULU": "consumer_cyclical",
    "DECK": "consumer_cyclical", "TPR": "consumer_cyclical",
    "BBY": "consumer_cyclical", "ROST": "consumer_cyclical",
    "TJX": "consumer_cyclical", "DPZ": "consumer_cyclical",

    # Consumer Staples
    "PG": "consumer_staples", "KO": "consumer_staples", "PEP": "consumer_staples",
    "EL": "consumer_staples",
    "CL": "consumer_staples", "KMB": "consumer_staples", "KHC": "consumer_staples",
    "CAG": "consumer_staples", "SJM": "consumer_staples", "CPB": "consumer_staples",
    "GIS": "consumer_staples", "MDLZ": "consumer_staples", "MNST": "consumer_staples",
    "STZ": "consumer_staples", "TAP": "consumer_staples", "CLX": "consumer_staples",

    # Energy
    "XOM": "energy", "CVX": "energy", "COP": "energy", "EOG": "energy",
    "OXY": "energy", "HAL": "energy", "SLB": "energy", "MPC": "energy",
    "PSX": "energy", "VLO": "energy", "HES": "energy", "FANG": "energy",
    "DVN": "energy", "MRO": "energy", "APA": "energy", "CTRA": "energy",
    "SWN": "energy", "CHK": "energy", "AR": "energy", "PR": "energy",

    # Industrials
    "CAT": "industrials", "BA": "industrials", "GE": "industrials", "HON": "industrials",
    "RTX": "industrials", "LMT": "industrials", "NOC": "industrials", "GD": "industrials",
    "DE": "industrials", "MMM": "industrials", "UPS": "industrials", "FDX": "industrials",
    "CSX": "industrials", "NSC": "industrials", "UNP": "industrials", "EMR": "industrials",
    "ROK": "industrials", "CARR": "industrials", "OTIS": "industrials",
    "TT": "industrials", "IR": "industrials",
    "CHWY": "industrials", "GWW": "industrials", "PCAR": "industrials",

    # Materials
    "LIN": "materials", "SHW": "materials", "APD": "materials", "ECL": "materials",
    "FCX": "materials", "NEM": "materials", "DOW": "materials", "DD": "materials",
    "PPG": "materials", "BLL": "materials", "AVY": "materials", "IP": "materials",
    "WRK": "materials", "PKG": "materials", "EMN": "materials", "CE": "materials",
    "CF": "materials", "MOS": "materials", "ALB": "materials",

    # Utilities
    "NEE": "utilities", "DUK": "utilities", "SO": "utilities", "D": "utilities",
    "AEP": "utilities", "SRE": "utilities", "EXC": "utilities", "PEG": "utilities",
    "ED": "utilities", "XEL": "utilities", "WEC": "utilities", "DTE": "utilities",
    "ETR": "utilities", "FE": "utilities", "ES": "utilities", "AEE": "utilities",
    "CMS": "utilities", "LNT": "utilities", "EIX": "utilities",
    "ATO": "utilities", "AWK": "utilities", "NI": "utilities",
    "PNW": "utilities", "CNP": "utilities", "NRG": "utilities", "PPL": "utilities",
    "PCG": "utilities", "CEG": "utilities", "VST": "utilities",

    # Real Estate
    "PLD": "real_estate", "AMT": "real_estate", "EQIX": "real_estate",
    "CCI": "real_estate", "PSA": "real_estate", "DLR": "real_estate",
    "O": "real_estate", "SPG": "real_estate", "WELL": "real_estate",
    "AVB": "real_estate", "EQR": "real_estate", "ESS": "real_estate",
    "ARE": "real_estate", "BXP": "real_estate",

    # Communication Services
    "NFLX": "communication",
    "DIS": "communication", "CMCSA": "communication", "T": "communication",
    "TMUS": "communication", "VZ": "communication", "CHTR": "communication",
    "LYV": "communication", "TTWO": "communication", "EA": "communication",
    "WBD": "communication", "PARA": "communication", "ROKU": "communication",
    "SNAP": "communication", "PINS": "communication", "TWTR": "communication",

    # Mid/Small cap liquidity additions
    "PAX": "technology", # PAX Labs is tech/Fintech,
    "THIN": "unknown", # Test ticker,
    "CHEAP": "unknown", # Test ticker,
    "FAIL": "unknown", # Test ticker,

    # More liquid research tickers
    "AA": "materials", "ACGL": "financials", "AFL": "financials",
    "AIG": "financials", "AIZ": "financials", "ALL": "financials",
    "AES": "utilities", "AGR": "utilities",
    "AKAM": "technology",
    "ALLE": "industrials", "AMCR": "materials",
    "AMTM": "technology",
    "APO": "financials", "APP": "technology",
    "ARES": "financials", "ARMK": "consumer_cyclical", "AVTR": "healthcare",
    "AXON": "industrials", "AXTA": "materials",
    "AZO": "consumer_cyclical", "BAH": "industrials",
    "BALL": "materials", "BAX": "healthcare",
    "BBWI": "consumer_cyclical", "BEN": "financials",
    "BG": "consumer_staples", "BIIB": "healthcare",
    "BIO": "healthcare", "BK": "financials",
    "BKR": "energy", "BLDR": "industrials",
    "BMRN": "healthcare", "BR": "financials",
    "BRO": "financials", "BSY": "technology",
    "BURL": "consumer_cyclical", "BWXT": "industrials",
    "BX": "financials", "CAH": "healthcare",
    "CAR": "consumer_cyclical", "CASY": "consumer_cyclical",
    "CBOE": "financials", "CBRE": "real_estate",
    "CCK": "materials", "CDNS": "technology",
    "CDW": "technology",
    "CELH": "consumer_staples",
    "CFLT": "technology", "CG": "financials",
    "CI": "healthcare", "CLF": "materials",
    "CME": "financials",
    "CNC": "healthcare", "CNM": "industrials", "COHR": "technology",
    "COIN": "financials", "CONY": "consumer_cyclical",
    "COO": "healthcare", "CPAY": "financials", "CPRT": "industrials",
    "CRL": "healthcare", "CSGP": "real_estate",
    "CSL": "industrials", "CSTM": "materials",
    "CTAS": "industrials", "CTLT": "healthcare",
    "CTSH": "technology", "CVNA": "consumer_cyclical",
    "CVS": "healthcare",
    "CZR": "consumer_cyclical", "DAL": "industrials",
    "DAY": "technology", "DBX": "technology",
    "DELL": "technology", "DFS": "financials",
    "DG": "consumer_cyclical", "DGX": "healthcare",
    "DHI": "consumer_cyclical",
    "DINO": "energy",
    "DKNG": "consumer_cyclical", "DLTR": "consumer_cyclical",
    "DOCU": "technology", "DOV": "industrials", "DUOL": "technology",
    "DV": "technology", "DVA": "healthcare",
    "EBAY": "consumer_cyclical", "EFX": "industrials",
    "ELY": "consumer_cyclical", "EME": "industrials", "ENPH": "technology",
    "EPAM": "technology", "EQH": "financials", "ERIE": "financials", "ESTC": "technology",
    "ETSY": "consumer_cyclical", "EVRG": "utilities", "EXAS": "healthcare", "EXPD": "industrials",
    "EXPE": "consumer_cyclical", "EXR": "real_estate",
    "FAST": "industrials",
    "FDS": "financials", "FFIV": "technology",
    "FI": "financials", "FICO": "technology", "FIVE": "consumer_cyclical",
    "FIX": "industrials", "FLEX": "technology",
    "FLR": "industrials", "FLS": "industrials",
    "FMC": "materials", "FNF": "financials",
    "FOX": "communication", "FOXA": "communication",
    "FSLR": "technology", "FTNT": "technology",
    "FTV": "industrials", "FXI": "financials",
    "GDDY": "technology", "GEHC": "healthcare",
    "GEN": "technology", "GFS": "technology",
    "GL": "financials", "GLW": "industrials", "GMED": "healthcare",
    "GNRC": "industrials", "GPC": "consumer_cyclical",
    "GPN": "financials", "GPS": "consumer_cyclical",
    "GRMN": "technology",
    "GTLS": "industrials", "GWRE": "technology", "H": "consumer_cyclical", "HAS": "consumer_cyclical", "HCA": "healthcare", "HIG": "financials", "HOLX": "healthcare", "HOOD": "financials",
    "HPE": "technology", "HPQ": "technology",
    "HRL": "consumer_staples", "HSIC": "healthcare",
    "HST": "real_estate", "HSY": "consumer_staples",
    "HUBB": "industrials", "HUBS": "technology",
    "HUM": "healthcare", "HWM": "industrials", "ICE": "financials", "IEX": "industrials",
    "IFF": "materials", "INTU": "technology", "IPG": "communication",
    "IQV": "healthcare",
    "IRM": "real_estate",
    "IT": "technology", "ITW": "industrials",
    "IVZ": "financials", "J": "consumer_cyclical",
    "JBHT": "industrials", "JBL": "technology",
    "JCI": "industrials", "JKHY": "technology",
    "JLL": "real_estate",
    "JNPR": "technology",
    "JWN": "consumer_cyclical", "K": "consumer_staples",
    "KDP": "consumer_staples",
    "KEYS": "technology",
    "KIM": "real_estate", "KKR": "financials", "KMI": "energy",
    "KMX": "consumer_cyclical", "KNX": "industrials", "KR": "consumer_staples",
    "KRC": "real_estate", "KSS": "consumer_cyclical",
    "L": "financials", "LDOS": "industrials",
    "LEN": "consumer_cyclical", "LHX": "industrials", "LKQ": "consumer_cyclical",
    "LPLA": "financials", "LVS": "consumer_cyclical",
    "LYB": "materials",
    "M": "consumer_cyclical",
    "MANH": "technology",
    "MAS": "industrials", "MAA": "real_estate",
    "MCK": "healthcare", "MCO": "financials",
    "MCW": "financials", "MGM": "consumer_cyclical",
    "MHK": "consumer_cyclical", "MIDD": "industrials",
    "MKC": "consumer_staples", "MKTX": "financials",
    "MLM": "materials", "MMC": "financials",
    "MO": "consumer_staples", "MOH": "healthcare",
    "MPWR": "technology", "MSCI": "financials", "MSI": "technology", "MTCH": "communication",
    "MTD": "healthcare",
    "MUSA": "consumer_cyclical",
    "NDAQ": "financials", "NDSN": "industrials",
    "NTAP": "technology", "NTRS": "financials",
    "NUE": "materials",
    "NVR": "consumer_cyclical", "NWL": "consumer_cyclical",
    "NWS": "communication", "NWSA": "communication",
    "NXPI": "technology",
    "OC": "industrials", "ODFL": "industrials",
    "OGN": "healthcare", "OKE": "energy",
    "OKTA": "technology", "OLN": "materials",
    "OMC": "communication", "ON": "technology",
    "ONTO": "technology",
    "ORLY": "consumer_cyclical", "OSK": "industrials",
    "PAYC": "technology", "PAYX": "technology", "PFG": "financials", "PGR": "financials",
    "PH": "industrials", "PHM": "consumer_cyclical", "PM": "consumer_staples", "PNR": "industrials", "POOL": "consumer_cyclical", "PRU": "financials",
    "PTC": "technology", "PWR": "industrials",
    "REG": "real_estate",
    "RGA": "financials", "RGLD": "materials",
    "RHI": "industrials", "RIVN": "consumer_cyclical",
    "RL": "consumer_cyclical", "RLI": "financials",
    "RMD": "healthcare", "ROL": "industrials",
    "ROP": "technology",
    "RPM": "materials", "RRC": "energy",
    "RS": "materials", "RSG": "industrials", "RVTY": "healthcare",
    "S": "technology", "SAIA": "industrials",
    "SASR": "financials", "SBAC": "real_estate",
    "SCI": "consumer_cyclical", "SEE": "materials",
    "SHEL": "energy", "SNA": "industrials", "SNPS": "technology",
    "SOLV": "materials",
    "SPGI": "financials", "SQ": "technology", "SSNC": "technology",
    "STE": "healthcare", "STLD": "materials",
    "STT": "financials", "STX": "technology", "SWK": "industrials",
    "SWKS": "technology", "SYF": "financials", "SYY": "consumer_staples", "TECH": "healthcare", "TFX": "healthcare", "TPL": "energy",
    "TPX": "consumer_cyclical", "TRGP": "energy",
    "TRMB": "technology", "TROW": "financials",
    "TRU": "industrials",
    "TTD": "technology",
    "TW": "technology", "TWLO": "technology", "TXT": "industrials",
    "TYL": "technology", "UAL": "industrials", "UDR": "real_estate",
    "UHS": "healthcare", "ULTA": "consumer_cyclical", "UNM": "financials",
    "URI": "industrials",
    "VFC": "consumer_cyclical",
    "VLTO": "industrials", "VMC": "materials",
    "VNO": "real_estate", "VRSK": "financials",
    "VRSN": "technology", "VTR": "real_estate",
    "VTRS": "healthcare",
    "WAB": "industrials", "WAT": "healthcare",
    "WBA": "consumer_staples",
    "WCC": "industrials",
    "WDC": "technology",
    "WFRD": "energy", "WH": "consumer_cyclical",
    "WHR": "consumer_cyclical", "WLK": "materials",
    "WM": "industrials", "WMB": "energy", "WRB": "financials",
    "WST": "healthcare", "WTW": "financials",
    "WY": "real_estate", "WYNN": "consumer_cyclical",
    "XPO": "industrials", "XYL": "industrials", "YUMC": "consumer_cyclical",
    "ZBRA": "technology",

    # ETFs — sector/specialized
    "SPY": "etf", "QQQ": "etf", "IWM": "etf", "DIA": "etf",
    "XLK": "etf", "XLF": "etf", "XLE": "etf", "XLV": "etf",
    "XLI": "etf", "XLB": "etf", "XLU": "etf", "XLRE": "etf",
    "XLC": "etf", "XLY": "etf", "XLP": "etf",
    "ARKK": "etf", "TLT": "etf", "IEF": "etf", "HYG": "etf",
    "LQD": "etf", "GDX": "etf", "GDXJ": "etf",
    "USO": "etf", "UNG": "etf", "SLV": "etf", "GLD": "etf",
    "EWJ": "etf", "EWZ": "etf",
    "EEM": "etf", "VWO": "etf", "VNQ": "etf",

    # Missing liquid research stocks
    "MSTR": "technology", "SHOP": "technology", "AFRM": "technology",
    "RBLX": "technology",
    "DASH": "technology",
    "LCID": "consumer_cyclical", "GME": "consumer_cyclical",
    "AMC": "consumer_cyclical", "BB": "technology",
    "NVAX": "healthcare", "MARA": "technology",
    "RIOT": "technology", "SOXX": "etf", "SMH": "etf",
    "TQQQ": "etf", "SQQQ": "etf",
    "BABA": "consumer_cyclical", "NIO": "consumer_cyclical",
    "LI": "consumer_cyclical", "XPEV": "consumer_cyclical",
}

# Build reverse lookup: sector → tickers
SECTOR_PRESETS: dict[str, list[str]] = {}
for ticker, sector in _SECTOR_MAP.items():
    if ticker == "AMZN":
        continue  # AMZN mapped to both; skip duplicate for presets
    SECTOR_PRESETS.setdefault(sector, []).append(ticker)


def get_sector(ticker: str) -> str:
    """Return the sector for a given ticker symbol, case-insensitive."""
    return _SECTOR_MAP.get(ticker.upper().strip(), "unknown")
